### PR TITLE
Now you can upload images locally

### PR DESCRIPTION
**Pull request by 0c0de**
I've added the upload images feature by using firebase storage, easy to setup and also easy to work with, If any problem occurs then contact me 😄

### CODE REVIEW

**Comment by chrisdesilva** [comment]
Testing locally and I got this error: 

AddCourt.js:126 Uncaught TypeError: _fire__WEBPACK_IMPORTED_MODULE_3__.default.collection is not a function at Object.AddCourt.addCourt [as onClick] (AddCourt.js:126)

Any idea what's causing that?

**Comment by chrisdesilva** [comment]
I reverted back to the previous commit to try to get it sorted out. Wondering if it has something to do with connecting storage to the database? I saw that an image was successfully added to storage when I submitted but I wasn't able to actually add the court with the image to the collection of courts.

**Comment by 0c0de** [comment]
Ok, now I'm working at my job but when I get home I'll take a look :+1:

**Comment by 0c0de** [comment]
Did you manage to get the upload working?

**Comment by chrisdesilva** [comment]
I gave it a shot but no luck. I set up storage on my Firebase account. Was there another step I missed to get it all set up?

**Comment by 0c0de** [comment]
I think I found a fix

**Comment by chrisdesilva** [comment]
Awesome. I'll test it out after work tonight. Thanks again for taking on this issue!

**Comment by 0c0de** [comment]
Sorry for not being active the past week, I was busy :disappointed:

**Pull request merged**
